const DONE = 'DONE';
const ONCHANGETASK = 'ONCHANGETASK';
const ONCHANGEREVIEW = 'ONCHANGEREVIEW';
const ONSAVE = 'ONSAVE';
const CREATE = 'CREATE';
const CANCEL = 'CANCEL';
const OPENMODAL = 'OPENMODAL';
const OPENCREATEMODAL = 'OPENCREATEMODAL';
const UNDONE = 'UNDONE';
export { DONE, UNDONE, ONCHANGETASK, ONCHANGEREVIEW, ONSAVE, CREATE, CANCEL, OPENMODAL, OPENCREATEMODAL }